#This file describes the key parameters of the reference experiment for the training (Table 1. in the article)

#WARNING: parameters should be in a list (even of size 1)


#Size of the state ($N_x$ in the article)
p: [36]

#Observation time sampling ($\Delta_t$ in the article) in MTU
dtObs: [0.05]

#Additive model noise standard deviation for DA (for 1 time step)
std_m: [0.06]

#Observation standard deviation ($\sigma^{\rm o}$ in the article)
std_o: [0.1]

#Fitering of the training set after DA (size of the window used for averaging in  number of time steps):
Nfil_train: [1]

#Time length of the simulation
T: [15.]

#Number of ensemble in the simulation
N: [1]

#seed for the random initialisation of the simulation
seed: [5]

#THE FOLLOWING PARAMETERS ARE CONSTANT (NOT IN A LIST)

#Type of obs (perfect/noisy)
obstype: 'noisy'

#Directory where to save the simualtions
savedir: 'simul/train'

#Template name of the files used in the experiments
template:
 #Initilisation file (generates by the true model)
 'initname': 'init-N{N}-seed{seed}.npy'

 #True simulation
 'truth': 'simul-truth-T{T}-N{N}-seed{seed}.npz'

 #Trunc simulation
 'trunc':  'simul-trunc-T{T}-N{N}-seed{seed}.npz'
